### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by zaherg**
Adding a note about using `--limit-cup` to limit the usage of the CPU

### CODE REVIEW

**Comment by alexellis** [comment]
Hi, thanks for the suggestion. It might be worth limiting CPU core usage by selecting which cores to target - via `docker run alexellis2/cpu-opt:2018-1-2 ./cpuminer --help`:

```
      --cpu-affinity    set process affinity to cpu core(s), mask 0x3 for cores 0 and 1
      --cpu-priority    set process priority (default: 0 idle, 2 normal to 5 highest)
```

**Comment by zaherg** [comment]
got it, so we should update the README file to include this info

**Comment by alexellis** [comment]
It doesn't really make sense to run a miner and then throttle the CPU.. is that something that is important for the way you want to mine? If so maybe we should add both of these bits of info for people.

**Comment by zaherg** [comment]
To be honest, my idea was like this, if you are running the script on some VPS providers they do have a policy against using the CPU for intensive work for long time, so if we limit the CPU usage using Docker option, this may and may not, prevent this companies from terminating the user account, plus he will be able to use the system for something else other than just mining.

This info can be useful especially with those who dont read the TOS, or dont have much technical experience with Docker.

at least this is was my idea when I edit the readme file

**Comment by alexellis** [comment]
Cool.. do you want to submit that paragraph (edited) and the two bits of info along with that?

**Comment by zaherg** [comment]
I'll try to rephrase them today, but you may need to recheck cause my english is not as good as yours for sure :D

**Review by alexellis — APPROVED** [review]
Thank you for the edit.

**Pull request merged**
